apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Arthur De Magalhaes <ademagalhaes@gmail.com>
    commit.image.appsody.dev/committer: Arthur De Magalhaes <ademagalhaes@gmail.com>
    commit.image.appsody.dev/date: Tue Feb 4 11:02:52 2020 -0500
    commit.image.appsody.dev/message: Updating deployment
    image.opencontainers.org/created: "2020-02-05T20:55:51-05:00"
    image.opencontainers.org/documentation: https://github.com/application-runtimes/sample-service-binding-consumer
    image.opencontainers.org/revision: ea49d6c25e4626c514d902c560f0205ca269cfc9-modified
    image.opencontainers.org/source: https://github.com/application-runtimes/sample-service-binding-consumer/tree/master
    image.opencontainers.org/url: https://github.com/application-runtimes/sample-service-binding-consumer
    stack.appsody.dev/authors: Mike Andrasak <andrasak@us.ibm.com>, Andy Mauer <ajmauer@us.ibm.com>,
      Scott Kurz <skurz@us.ibm.com>, Adam Wisniewski <awisniew@us.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/java-openliberty:0.1
    stack.appsody.dev/created: "2020-02-05T13:14:18Z"
    stack.appsody.dev/description: Open Liberty & OpenJ9 using Maven
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/java-openliberty:0.1.5
    stack.appsody.dev/title: Open Liberty
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: service-binding-consumer
    stack.appsody.dev/id: java-openliberty
    stack.appsody.dev/version: 0.1.5
  name: service-binding-consumer
spec:
  applicationImage: consumer
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-openliberty
  version: 1.0.0
status: {}
